#!/bin/bash

# Use the branch name as the start of the commit message
branchName=$(git symbolic-ref --short -q HEAD)
firstLine=$(head -n1 $1)

if [ $branchName != $(git symbolic-ref -q HEAD) ] ;then
  if [ -z "$firstLine"  ] ;then #Check that this is not an amend by checking that the first line is empty
    sed -i '.bak' "1s/^/$branchName/" $1
  fi
fi

